{{cookiecutter.project_name}}/pyproject.toml
- `license = "{{cookiecutter.license}}" `
- `readme = "README.md"` avoids `long description` error  during pypi release
=> typo fix for license and added readme = "README.md" to avoid pypi release error about wrong `long description`

cookiecutter.json, hooks/post_gen_project.py, {{cookiecutter.project_name}}/.github/workflows/deploy-docs.yaml, {{cookiecutter.project_name}}/.github/workflows/pypi-publish.yaml, {{cookiecutter.project_name}}/Makefile, {{cookiecutter.project_name}}/pyproject.toml, {{cookiecutter.project_name}}/src/{{cookiecutter.__project_slug}}/schema/{{cookiecutter.__project_slug}}.yaml, {{cookiecutter.project_name}}/tests/test_data.py
- ~my_awesome_schema~ => `{{cookiecutter.__project_slug}}`
- Added docs extras in the toml file use by doc deploy workflow.
- Added placeholder for description in toml file -> "github_token_for_pypi_deployment": "PYPI_PASSWORD ~(leave blank if not a python project)~"
- `class_uri: schema:Thing` converted from a `list` to a scalar entity
- `{% if cookiecutter.use_schemasheets == "Yes" %}` =="Yes" was missing
=> Placeholder updates and bug fixes

README.md, cookiecutter.json
```
"__project_slug": "{{ cookiecutter.project_name|lower()|replace(' ', '_')|replace('-', '_') }}",
```
generates an error in `cruft create` if the version of click installed > 8.0.4.  (I am trying a bare install of cruft in prep for linkml tutorial, as a test of the recipe). 
I am not quite sure how to make this a requirement.  For now I just added it to the README we want to go back to a slightly less helpful rewrite rule here and just fail the project creation if the naming convention is not quite right?  
Another option is to have the user wrap the project creation in a virtual environment via instructions in the README.
=> bare cruft installs click at > 8.0.4, then syntax errors on cruft create b/c of 

cookiecutter.json, {{cookiecutter.project_name}}/mkdocs.yml
Remove `google_analytics_gtag` from cookiecutter prompts and `mkdocs.yaml`. Replace it with a commented-out block to help users get started if they want to opt-in to Google Analytics.
Fixes #23
=> Remove google_analytics_gtag field

{{cookiecutter.project_name}}/Makefile
This PR allows users to bypass https://github.com/linkml/linkml-project-cookiecutter/issues/33 but is not full fix 
(i.e. git repo creation is done in step 8 but is required for step 4, so possible design fault).
=> fix(poetry): workaround 'not a git project'

{{cookiecutter.project_name}}/Makefile
This PR seems to fix `make setup` errors:
```
(baselink-py3.10) $ make setup
./utils/get-value.sh: 4: Bad substitution
./utils/get-value.sh: 4: Bad substitution
poetry install
This does not appear to be a Git project
```
=> fix(make): updated makefile

{{cookiecutter.project_name}}/Makefile
This PR is minor updates to Makefile:
- cleanup docs/* folder
- commitlint friendly commit message
- add version.py to git control
=> chore(makefile): minor updates for make clean/setup

{{cookiecutter.project_name}}/Makefile
This PR is followup to #38 and fully fixes #33.
We should not remove .git/ because step 8 in README requires git repository.
=> fix(makefile): keep git repo, needed in step 8

README.md
This PR removes unnecessary `poetry install` step because it does nothing.
```]
$ poetry install
Installing dependencies from lock file
No dependencies to install or update
/home/noel/git/hub/lmodel/uco/uco-identity/uco_identity does not contain any element
```
Closes https://github.com/linkml/linkml-project-cookiecutter/issues/37
=> docs: remove superfluous poetry step

README.md
This PR bumps up click version
=> chore(readme): update click version

{{cookiecutter.project_name}}/.github/workflows/deploy-docs.yaml
Use available Makefile rules in documentation deployment workflow rather than manually writing the commands.
=> Use Makefile targets for documentation deployment

{{cookiecutter.project_name}}/.github/workflows/deploy-docs.yaml
This PR ensures an "about.md" exists in generated website (avoids 404 not found).
=> fix(github): ensure about.md is handled

.codespellrc, .github/workflows/codespell.yml, README.md, {{cookiecutter.project_name}}/Makefile, {{cookiecutter.project_name}}/project/jsonld/{{cookiecutter.__project_slug}}.jsonld
But may be since a template I should just leave it to "typos fixed"?
=> Codespell: config, workflow + typos fixed

.gitignore, README.md, {{cookiecutter.project_name}}/Makefile, {{cookiecutter.project_name}}/tests/test_data.py
Fixes #81 
Mainly this is updating the `README` to give instructions on getting set up using `pipx` instead of creating the "wrapper" Poetry environment.
While making sure that everything in the `README` works out of the box I made two additional changes:
* Updated a few of the git-related `Makefile` targets so that there are no uncommitted files still hanging around after the initial commit
* Removed the `git-init` target from `install` and added it to `setup`. There are valid reasons you might want to run `make install` again later and you don't want to call `git init` at that point.
* Removed the instruction to call `make deploy` from the `README`. I don't think we want to encourage people doing this manually especially since we have a GitHub Action that does it.
* Fixed the unit test …
=> Rewrite README instructions to use pipx

README.md, {{cookiecutter.project_name}}/.github/workflows/deploy-docs.yaml
Describe how to configure the GitHub project. The PR also changes the action to no longer require write access on project level. Instead it only sets the minimal required permissions. It gives write permission only to the job that needs it (pages deployment).
I also added a link to the new ~~unreleased~~ section on "manage releases" in the linkML how-tos (https://github.com/linkml/linkml/pull/1765).
Closes #61
=> Describe how to deploy docs to gh-apges & limit required permissions for build-doc action

{{cookiecutter.project_name}}/.github/workflows/deploy-docs.yaml, {{cookiecutter.project_name}}/.github/workflows/main.yaml, {{cookiecutter.project_name}}/.github/workflows/pypi-publish.yaml
No need to use a special action for setting up poetry. `pipx` is available by default and can be used to install poetry. 
Installing poetry this way also has the advantage that is is in its own isolated environment.
=> Switch actions to pipx-installing poetry

{{cookiecutter.project_name}}/Makefile
Ensure that gendoc copies all custom docs, including subdirs and other datatypes. Both are important as we, for example, want to be able to link images as well as other data in our docs.
=> Ensure that gendoc copies all custom docs

{{cookiecutter.project_name}}/Makefile
This PR updates Makefile to avoid multiple commit messages saying "initial commit" as user may run `make setup` multiple times => commit history looks funny with multiple "initial commits".
=> chore: 1st change make setup commit msg

{{cookiecutter.project_name}}/Makefile, {{cookiecutter.project_name}}/config.env
This PR does the following:
- improved variable names and better documentation  in `config.env` and `makefile`
- introduce `LINKML_ENVIRONMENT_FILE`  var for custom configuration location. For example to hide the file via `.config.yaml` or `.config/generators.yaml` or some other odd reason.
- Add some logic to Makefile to use environment variables as action triggers
1. set typescript environment variable (args) to trigger gen-typescript
2. set java environment variable (args) to trigger gen-java
3. set owl environment variable (args) if rdfs is needed (https://github.com/linkml/linkml/issues/1453)
This PR replaces  #69
=> feat: 3rd use environment vars to workaround issues

README.md
This PR updates README with few things
- configure global proxy server (sandboxed users) to avoid `poetry self add ....` failures
- cofigure project proxy server (sandboxed users)
- update configuration text around `config.yaml` and `config.env`
=> docs(readme): add poetry proxy; updated config steps

README.md
This PR updates README to communicate that `cruft create` fails if target directory already exists, and that `cruft create -f` is alternative syntax. My use case is pre-existing non-linkml project with same name as linkml `project_name`.
=> docs(readme): allow overlaying into existing non-linkml project

{{cookiecutter.project_name}}/Makefile
This PR is bug fix for issues introduced in previous PR (probably #94)
- Fixes error:  `Makefile:130: *** missing separator.  Stop.`  by using tab not spaces.
- Ensure `typescript/` directory exists
- Ensure `owl/` directory exists
- Using  `gen-owl -o` does not work (need to redirect instead)
=> fix(makefile): fix some minor issues

{{cookiecutter.project_name}}/pyproject.toml
I was hitting an error where the generated docs wouldn't render the mermaid class diagrams. Upgrading to the latest plugin version resolved the issue.
=> Update to the latest mkdocs-mermaid2-plugin

{{cookiecutter.project_name}}/.github/workflows/deploy-docs.yaml, {{cookiecutter.project_name}}/.github/workflows/test_pages_build.yaml
This PR seeks to add a GitHub Action workflow that will run everytime there is a new PR and create a link to preview the docs within that PR. It will also run everytime there is a new commit that is piled on top of commits in the open PR.
One of the pros of having this workflow will be that we won't need to create forks of schema repos just for the purpose of being able to create its own documentation site.
To see an example, you can look at the workflow file in action in the NMDC schema repo: https://github.com/microbiomedata/nmdc-schema/pull/2057
Inspiration from https://github.com/linkml/linkml/issues/2029
=> GitHub Action workflow to preview documentation changes in PRs

.github/workflows/codespell.yml, cookiecutter.json
This PR adds "copy without render" placeholder to `cookiecutter.json` per [documentation](https://cookiecutter.readthedocs.io/en/2.6.0/advanced/copy_without_render.html):
_To avoid rendering directories and files of a cookiecutter, the _copy_without_render key can be used in the cookiecutter.json._ 
**Justification**
I was testing  #118 and cookiecutter was failing with huge stracktrace, and after much troubleshooting this PR fixed the issue by skipping the JS file.
``` 
│ ╭──────────────────────────────────── locals ────────────────────────────────────╮ │
│ │ rewrite_traceback_stack = <function rewrite_traceback_stack at 0x7f682b1d8820> │ │
│ │                    self = <cookiecutter.environment.StrictEnvironment object   │ │
│ │                           at 0x7f682b826860> …
```
=> chore: cookiecutter copy-without-rendor support

README.md, {{cookiecutter.project_name}}/pyproject.toml
I have tested Poetry-2.0 in our repo here https://github.com/nfdi4cat/pid4cat-model/pull/36. This PR switches as much as possible to the PEP 621 standard. The few remaining `[tool.poetry....]` sections cannot be converted to PEP 621 but have to stay.
To install the development packages, run `poetry install --with=dev`. Using `poetry install` only installs the minimum which is the model and the linkml-runtime.
Due to PEP 621 conformance switching to Poetry 2.0 is also a good first step to move to [uv](https://docs.astral.sh/uv/) next 😄
=> Update to Poetry 2.0

README.md, cookiecutter.json, {{cookiecutter.project_name}}/Makefile, {{cookiecutter.project_name}}/README.md, {{cookiecutter.project_name}}/config.public.mk, {{cookiecutter.project_name}}/config.yaml, {{cookiecutter.project_name}}/justfile, {{cookiecutter.project_name}}/project.justfile
Adds a `justfile` with tasks for the [just](https://github.com/casey/just/) command runner.
The added commands should match the current `makefile`. While working on this I slightly simplified the makefile/config, e.g. to use cookiecutter-parameters / env.vars more consistent.
Closes #120
=> Add task definitions for just as alternative command runner

{{cookiecutter.project_name}}/mkdocs.yml, {{cookiecutter.project_name}}/tablesort.js
Followup from https://github.com/linkml/linkml-project-cookiecutter/pull/99
Adds sorting functionality to tables in mkdocs documentation.
=> mkdocs sort functionality

README.md
I also added a note on the (new-to-me) option to have poetry 1.0 and 2.0 installed at the same time.
Closes #129
=> Mention poetry 2.0 requirement

{{cookiecutter.project_name}}/.github/workflows/deploy-docs.yaml, {{cookiecutter.project_name}}/.github/workflows/test_pages_build.yaml, {{cookiecutter.project_name}}/pyproject.toml
After the upgrade to poetry 2, the Python and linkml-runtime dependencies are declared at two places in `pyproject.toml`. This removes the redundancy. 
It was just an oversight in #128. `poetry check` does not complain and the project setup and installation works fine even with the redundant spec as long as there is no contradiction.
This also fixes the installation in the docs-related gh-actions (#133): 
- mkdocs-related packages are installed as dev-dependencies and not as extras.
Closes #133
=> Remove redundant specs from pyproject.toml

{{cookiecutter.project_name}}/Makefile, {{cookiecutter.project_name}}/justfile
As a result of correcting the example-folder structure in #136, copying of the folder has to be done recursively now.
=> Copy example folder recursively in make & just commands
